### ISSUE TITLE
如何添加集成

### ISSUE THREAD

**Issue by whowho182** [MrChanGG/ha_face_detect#1]
按你的步骤都操作完了，怎么调用？需要添加集成？集成名字找不见呀

**Comment by Wing-Sing** [comment]
概览-编辑仪表盘-未使用实体 然后会出现实体名称

**Comment by whowho182** [comment]
![1644651087(1)](https://user-images.githubusercontent.com/49549058/153701877-a864d562-8e70-4816-968d-112383af0b48.png)
代码没错吧？未使用实体发现不了。

**Comment by Wing-Sing** [comment]
你把引号都删除了，比如app_id:"引号务必加上"  其他也是一样，把该加的引号加上

**Comment by Wing-Sing** [comment]
只有scan是没有引号的，其他务必加引号

**Comment by whowho182** [comment]
最后找见问题，是我还有个sensor 获取路由信息的传感，重复了，删除就好了。谢谢
